name: lite_agent_core_dart
description: LiteAgent Core package
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.0
  http: ^1.2.1
  dart_openai: ^5.1.0
  modbus_client_tcp: ^1.2.1
  modbus_client_udp: ^1.2.1
  modbus_client_serial: ^1.2.1+1
  json_rpc_2: ^3.0.2

  openapi_dart: ^0.1.2
  openrpc_dart: ^0.1.2
#    path: /Users/jan/Project/openspec_dart/openrpc_dart
  opentool_dart: ^0.1.3
#    path: /Users/jan/Project/openspec_dart/opentool_dart
  openmodbus_dart: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.2.0
