name: lite_agent_core_dart
description: LLM AI Agent sessions service in Dart.
version: 0.7.0
repository: https://github.com/LiteVar/lite_agent_core_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  http: ^1.2.2

  # OpenAI style api support
  dart_openai_sdk: ^5.2.0

  # OpenSpec support
  opentool_dart: ^0.3.0
  openapi_dart: ^0.1.3
  openrpc_dart: ^0.1.3
  openmodbus_dart: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
