name: lite_agent_core
description: LiteAgent Core package
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dart_openai: ^5.1.0
  http: ^1.2.1
  openapi_dart: ^0.1.2
  openrpc_dart: ^0.1.1
  opentool_dart: ^0.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.2.0
