name: lite_agent_core_dart
description: LLM AI Agent sessions service in Dart.
version: 0.1.0
repository: https://github.com/LiteVar/lite_agent_core_dart

environment:
  sdk: ^3.3.4

dependencies:
  uuid: ^4.4.0
  http: ^1.2.1
  json_annotation: ^4.9.0

  # OpenAI style api support
  dart_openai: ^5.1.0

  # Modbus Protocol support
  modbus_client: ^1.2.1
  modbus_client_tcp: ^1.2.1
  modbus_client_udp: ^1.2.1
  modbus_client_serial: ^1.2.1+1

  # json-rpc 2.0 support
  json_rpc_2: ^3.0.2

  # OpenSpec support
  openapi_dart: ^0.1.3
  openrpc_dart: ^0.1.3
  opentool_dart: ^0.1.3
  openmodbus_dart: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
